Enable publishing any tag name
spatie/laravel-package-tools pull request #105
Opened 2023-08-10 21:05 UTC by misenhower

This PR adds a new `->publish($tag)` method on the install command that enables you to publish arbitrary tag name.s For instance, we might use `->publish('nova')` to publish Nova resources from our package.

This way, we don't need to add an individual method for each possible tag name. I've also replaced all the individual `$shouldPublish***` properties with the new `$publishes` array.

Let me know what you think. Thanks!!

2023-08-11 07:42 UTC, freekmurze requested changes
Seems nice, thanks!

2023-08-11 07:42 UTC, freekmurze commented on src/Commands/InstallCommand.php
> +    public function publish(string $tag): self
Make this function variadic, so people can pass multiple tags. 

```php
$this->publish('config', 'assets');
```

2023-08-22 18:02 UTC, misenhower commented
Hey, sorry for the delay. I just pushed a change for that. Let me know what you think!

2023-08-23 09:04 UTC, merged

2023-08-23 09:04 UTC, freekmurze commented
Thanks!