Allow command optimization
spatie/laravel-package-tools pull request #147
Opened 2024-10-28 23:52 UTC by Riley19280

Laravel [added support](https://github.com/laravel/framework/pull/52928) for integrating with the base `optimize` and `optimize:clear` commands, so this PR adds support for that functionality like so:
```php
$package->optimizes(Command::class, ClearCommand::class);
```

Note that this PR depends on [L11 development support](https://github.com/spatie/laravel-package-tools/pull/146) for testing, so those changes are also shown

2024-12-09 16:28 UTC, freekmurze commented
Could you rebase against main?

2024-12-11 09:43 UTC, freekmurze requested changes
Could you also add a nice example of this functionality to the docs?

2024-12-11 09:43 UTC, freekmurze commented on src/Package.php
> +            'optimize' => $optimize,
This will be a command right? Rename the variable to `optimizeCommand`, same for `clearCommand` and `packagenameKey`

2025-01-22 08:51 UTC, freekmurze commented
Closing due to inactivity

2025-01-22 08:51 UTC, closed without merging

2026-08-30 09:42 UTC, Josefikos commented
I'm interested in completing this feature. 

Would be beneficial allowing adding commands for optimize / clear directly from `hasCommands` as syntax sugar besides own `hasOptimization` method?

```php
$package->hasCommands([
  SimpleCommand::class => [
     'optimize' => true,
     'clear' => true,
  ],
]);
```