Fix for publishing view files that has its custom namespace
spatie/laravel-package-tools pull request #69
Opened 2022-10-10 12:52 UTC by askdkc

When your package view uses custom namespace, published view ignores the namespace and keeps using its package name for vendor-view's directory name.

For example, imagine you create a package that has some sort of image gallery. And you choose 'laravel-images' for your package view's namespace.

Now someone downloaded your package then decided to customize the views. So the person ran `php artisan vendor:publish` command to publish the views from this package.

But [according this sources](https://github.com/spatie/laravel-package-tools/blob/11cdf05a5d747778fad2c098e86cd48d20917e37/src/PackageServiceProvider.php#L65-L69) `laravel-package-tools` uses package name for its base_path and namespace and ignoring actual view namespace which the package creator specified.

So no matter how the user modifies the published views, Laravel couldn't find the published view files.

This PR provides a fix for this problem.

2022-10-10 15:57 UTC, freekmurze requested changes

2022-10-10 15:57 UTC, freekmurze commented on src/PackageServiceProvider.php
> +                } else {
Could you avoid having to use else by extracting this to a function?

Could you also add tests for this?

2022-10-10 16:58 UTC, askdkc reviewed
@freekmurze OK. I just avoid if-else statement and also added test for this

2022-10-11 06:37 UTC, merged

2022-10-11 06:37 UTC, freekmurze commented
Thanks!